package ws18.model;

public enum EventType {
    TOKEN_VALIDATION_REQUEST,
    TOKEN_VALIDATION_FAILED,
    MONEY_TRANSFER_REQUEST,
    TOKEN_REQUEST,
    TOKEN_VALIDATED,
    TOKEN_GRANTED
}
