package ws18.model;

public enum EventType {
    TOKEN_VALIDATION_REQUEST,
    TOKEN_VALIDATION_FAILED,
    MONEY_TRANSFER_REQUEST,
    REQUEST_FOR_NEW_TOKENS,
    TOKEN_GENERATION_RESPONSE,
    //Token Retrieval
    RETRIEVE_TOKENS,
    RETRIEVE_TOKENS_RESPONSE,
}
